### ISSUE TITLE
iscsi session remains on old node when pod migrates during outage

### ISSUE THREAD

**Issue by tobad357** [hpe-storage/csi-driver#67] opened 2019-11-05 03:16 UTC
We have run a scenario where we do the following

1. Reboot node 1 where pod that uses a volume runs
2. While node 1 is down delete the pod
3. Pod gets reschedule to other node but won't come up due to "Multi-Attach error for volume"
    This is due to that the volumeattachment resource still exists

4. Once node comes up volumeattachment gets cleaned up but the iscsi session still stays on the old node so the pod can't come up

Expected is that
1. On node failure a pod should be able to move quickly
2. On node reboot iscsi session should be cleared up if a volumeattachment doesn't exist for the node anymore

**Comment by tobad357** [comment] 2019-11-05 15:46
This is probably same as #69

**Comment by shivamerla** [comment] 2019-11-05 18:15
closing this one as duplicate of #69

**Closed by shivamerla** 2019-11-05 18:15 UTC
